name = "your-project-name" # Replace with your project name
compatibility_date = "2025-04-06" # Current date, adjust as needed

[build]
command = "npm run build" # Build command
pages_build_output_dir = ".next" # Output directory for Next.js

[build.environment]
NODE_VERSION = "20" # Node.js version 20

[env.production]
command = "npm start" # Runtime command (optional, mostly for Workers, not Pages)
